spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: oj-backend-user-service
          uri: lb://oj-backend-user-service
          predicates:
            - Path=/api/user/**
        - id: oj-backend-question-service
          uri: lb://oj-backend-question-service
          predicates:
            - Path=/api/question/**
        - id: oj-backend-judge-service
          uri: lb://oj-backend-judge-service
          predicates:
            - Path=/api/judge/**
        - id: oj-backend-post-service
          uri: lb://oj-backend-post-service
          predicates:
            - Path=/api/post/**
  application:
    name: oj-backend-gateway
  main:
    web-application-type: reactive
server:
  port: 8101

knife4j:
  # 聚合swagger文档
  gateway:
    enabled: true
    strategy: discover
    discover:
      enabled: true
      version: swagger2


